
  # Feign Client (User Service) URL

  user:
    microservice:
      url: https://mymulya.com

  #DataBase Configuration
  spring:
    datasource:
      url: jdbc:mysql://192.168.0.135:3306/production
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver


  # Enable MultiPart File uploads
    servlet:
      multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  # Logging configuration to suppress harmless async warnings
  logging:
    level:
      org.springframework.web.context.request.async: ERROR
      org.apache.coyote.http11.Http11Processor: ERROR

