
# Feign Client (User Service) URL

user:
  microservice:
    url: https://mymulya.com

#DataBase Configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/production
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver