
server:
  port: 8096

#DataBase Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/production
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# Enable MultiPart File uploads
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB


user:
  microservice:
    url: http://localhost:8083

# Logging configuration to suppress harmless async warnings
logging:
  level:
    org.springframework.web.context.request.async: ERROR
    org.apache.coyote.http11.Http11Processor: ERROR

# Connecting prod
#  profiles:
#    active: prod