
# Feign Client URL

user:
  microservice:
    url: http://154.210.228.26

#DataBase Configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver